version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - postgres
    php:
        build: .docker
        restart: always
        volumes:
#            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
#            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        user: www-data
        env_file:
            - .env
            - .env.local
    postgres:
        image: postgres:10.1
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - postgres-data-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: tq
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        env_file:
            - .env
            - .env.local
            
volumes:
    postgres-data-volume: #> docker volume create --name postgres-data-volume -d local
        external: true
