# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    RiverRing\Quest\:
        resource:
            '../src/'
        exclude:
            - '../src/Bridge/Symfony/Kernel.php'
            - '../src/Domain/Model/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    RiverRing\Quest\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller/'
        tags: ['controller.service_arguments']

    RiverRing\OwlOrm\Dbal\Pdo\LazyPdoProvider:
        arguments:
            $dsn: 'pgsql:host=%env(resolve:POSTGRES_HOST)%;port=%env(resolve:POSTGRES_PORT)%;dbname=%env(resolve:POSTGRES_DB)%'
            $user: '%env(resolve:POSTGRES_USER)%'
            $pass: '%env(resolve:POSTGRES_PASSWORD)%'

    RiverRing\OwlOrm\Dbal\Pdo\PdoProvider: '@RiverRing\OwlOrm\Dbal\Pdo\LazyPdoProvider'

    RiverRing\OwlOrm\Dbal\Pdo\GeneralPdoFactory: ~
    RiverRing\OwlOrm\Dbal\Pdo\PdoFactory: '@RiverRing\OwlOrm\Dbal\Pdo\GeneralPdoFactory'

    _instanceof:
        RiverRing\OwlOrm\Mapping\Mapper:
            tags: [ 'app.mappers' ]

    RiverRing\OwlOrm\Mapping\MapperRegistry:
        arguments:
            $mappers: !tagged_iterator 'app.mappers'

    RiverRing\OwlOrm\Dbal\Driver\PostgresDriver: ~

    RiverRing\OwlOrm\Dbal\Driver\Driver: '@RiverRing\OwlOrm\Dbal\Driver\PostgresDriver'
